- hosts: k8smaster1
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  
  tasks:
   
    - name: Create a JIRA issue
      uri:
        url: https://your.jira.example.com/rest/api/2/issue/
        user: your_username
        password: your_pass
        method: POST
        body: "{{ lookup('file','/userdata/theVerizonTask/project/templates/issue.json.j2',errors=warn) }}"
        force_basic_auth: yes
        status_code: 201
        body_format: json
      ignore_errors: yes

    - name: check issue.json existance
      stat:
        path: /tmp/issue.json
      register: stat_result

#    - debug: msg="{{ stat_result.stat }}"
   
    - name: copy template to remote
      template:
        src: issue.json.j2
        dest: /tmp/issue.json
      when: not stat_result.stat.exists
